import psycopg2

conn = psycopg2.connect(database='zinu_db', user='zinu', password='8197', host='localhost', port='5432')
cr = conn.cursor()
cr.execute("insert into category (id, code, name) values(1, 1, 'toothpaste');")
cr.execute("insert into category (id, code, name) values(2, 2, 'socks');")
cr.execute("insert into category (id, code, name) values(3, 3, 'football');")
cr.execute("insert into category (id, code, name) values(4, 4, 'jersey');")
cr.execute("insert into category (id, code, name) values(5, 5, 'tracksuit');")
cr.execute("insert into category (id, code, name) values(6, 6, 'jacket');")
cr.execute("insert into category (id, code, name) values(7, 7, 'hoodie');")
cr.execute("insert into category (id, code, name) values(8, 8, 'headband');")
cr.execute("insert into category (id, code, name) values(9, 9, 'ring');")
cr.execute("insert into category (id, code, name) values(10, 10, 'jeans');")
cr.execute("insert into category (id, code, name) values(11, 11, 't-shirt');")
cr.execute("insert into category (id, code, name) values(12, 12, 'shirt');")
cr.execute("insert into category (id, code, name) values(13, 13, 'Underwear');")
cr.execute("insert into category (id, code, name) values(14, 14, 'vest');")
cr.execute("insert into category (id, code, name) values(15, 15, 'leggings');")
cr.execute("insert into category (id, code, name) values(16, 16, 'slippers');")
cr.execute("insert into category (id, code, name) values(17, 17, 'sandals');")
cr.execute("insert into category (id, code, name) values(18, 18, 'tennis-racquets');")
cr.execute("insert into category (id, code, name) values(19, 19, 'table-tennis racquets');")
cr.execute("insert into category (id, code, name) values(20, 20, 'sunglasses');")
cr.execute("insert into product (id, name, cost_price, sale_price) values (1,'Colgate', 20.00, 35.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (2,'Nike socks', 10.00, 20.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (3,'Adidas football',60.00, 75.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (4,'Reebok jersey', 15.00, 20.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (5,'Nike tracksuit', 10.00, 12.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (6,'Adidas jacket', 25.00, 35.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (7,'Reebok hoodie', 600.00, 835.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (8,'Nike headband', 35.00, 50.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (9,'Adidas ring', 320.00, 535.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (10,'Reebok jeans', 1120.00, 1235.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (11,'Nike t-shirt', 570.00, 635.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (12,'Reebok shirt', 800.00, 975.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (13,'Adidas Underwear', 1200.00, 1435.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (14,'Adidas vest', 250.00, 400.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (15,'Reebok leggings', 2000.00, 3500.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (16,'Nike slippers', 25.00, 40.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (17,'Nike sandals', 820.00, 935.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (18,'Adidas tennis-racquets', 12.00, 15.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (19,'Reebok table-tennis-racquets', 420.00, 535.00);")
cr.execute("insert into product (id, name, cost_price, sale_price) values (20,'Puma sunglasses', 200.00, 350.00);")
conn.commit()
cr.close()
conn.close()
